#!/usr/bin/env bash
# Creates shopify.app.<slug>.toml for one merchant's custom-distribution app,
# from shopify.app.toml (the shared template). Then:
#   npx shopify app deploy --config <slug>
# and register the app's secret with the worker (PUT /admin/apps/<client_id>).
set -euo pipefail

if [ $# -lt 2 ]; then
  echo "usage: $0 <slug> <client_id> [app name]" >&2
  echo "  e.g. $0 croatisimo 1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d" >&2
  exit 64
fi

slug=$1
client_id=$2
name=${3:-"MPT — plaćanje QR kodom"}
cd "$(dirname "$0")/.."

[[ $slug =~ ^[a-z0-9-]+$ ]] || { echo "slug: only a-z 0-9 -" >&2; exit 65; }
[[ $client_id =~ ^[A-Za-z0-9]{16,64}$ ]] || { echo "client_id looks wrong" >&2; exit 65; }
out="shopify.app.$slug.toml"
[ -e "$out" ] && { echo "$out already exists" >&2; exit 73; }

sed -e "s|^client_id = .*|client_id = \"$client_id\"|" \
    -e "s|^name = .*|name = \"$name\"|" \
    -e "1,3c\\
# MPT for Shopify — custom-distribution app for: $slug\\
# Generated by scripts/new-merchant-app.sh from shopify.app.toml; keep the two\\
# in sync. Deploy with: npx shopify app deploy --config $slug" \
    shopify.app.toml > "$out"

echo "wrote $out"
echo "next: npx shopify app deploy --config $slug"
