#!/usr/bin/env bash
# Creates shopify.app.<slug>.toml for one merchant's custom-distribution app,
# from shopify.app.toml (the shared template). Then:
#   ./scripts/deploy-app.sh <slug>
# and register the app's secret with the worker (PUT /admin/apps/<client_id>).
#
# --worker-url points the app (install, OAuth, webhooks, extension API) at a
# standalone worker for this merchant instead of the shared one.
set -euo pipefail

usage() {
  echo "usage: $0 <slug> <client_id> [--name \"App name\"] [--worker-url https://host]" >&2
  echo "  e.g. $0 croatisimo 1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d --name \"MPT — Croatisimo\"" >&2
  exit 64
}
[ $# -ge 2 ] || usage
slug=$1
client_id=$2
shift 2
name="MPT — plaćanje QR kodom"
worker_url=""
while [ $# -gt 0 ]; do
  case $1 in
    --name) name=${2:?}; shift 2 ;;
    --worker-url) worker_url=${2:?}; shift 2 ;;
    *) usage ;;
  esac
done
cd "$(dirname "$0")/.."

shared_url="https://mpt-shopify.domovina.ai"
worker_url=${worker_url%/}
[[ $slug =~ ^[a-z0-9-]+$ ]] || { echo "slug: only a-z 0-9 -" >&2; exit 65; }
[[ $client_id =~ ^[A-Za-z0-9]{16,64}$ ]] || { echo "client_id looks wrong" >&2; exit 65; }
[ -z "$worker_url" ] || [[ $worker_url =~ ^https://[a-z0-9.-]+$ ]] || { echo "worker-url: https://host, no path" >&2; exit 65; }
out="shopify.app.$slug.toml"
[ -e "$out" ] && { echo "$out already exists" >&2; exit 73; }

sed -e "s|^client_id = .*|client_id = \"$client_id\"|" \
    -e "s|^name = .*|name = \"$name\"|" \
    -e "s|$shared_url|${worker_url:-$shared_url}|g" \
    -e "1,6c\\
# MPT for Shopify — custom-distribution app for: $slug\\
# Generated by scripts/new-merchant-app.sh from shopify.app.toml; keep the two\\
# in sync. Deploy with: ./scripts/deploy-app.sh $slug" \
    shopify.app.toml > "$out"

echo "wrote $out (worker: ${worker_url:-$shared_url})"
echo "next: ./scripts/deploy-app.sh $slug"
